### PR TITLE
feat: untunned spacecraft rate controller

### PR DESCRIPTION
**Pull request by Pedro-Roque**
Adding spacecraft rate controller.

Next: adding direct allocation of inputs

### CODE REVIEW

**Review by Jaeyoung-Lim — APPROVED** [review]
Awesome, thanks!

Can you run this on any of the space craft models yet? Maybe the 3D case?

**Comment by Pedro-Roque** [comment]
It runs on the 2D model but didn't test it on the 3D one. Should work the same though

**Comment by Jaeyoung-Lim** [comment]
@Pedro-Roque But the force input of the MPC is in three dimensions, wouldn't this be a problem?

**Comment by Pedro-Roque** [comment]
> @Pedro-Roque But the force input of the MPC is in three dimensions, wouldn't this be a problem?

No because it allocates only what it can - so if you give a setpoint in height it won't track it. But if you give a setpoint in the plane it won't be a problem.

**Pull request merged**
